controls:
  CheckBoxControl:
    display_name: Checkbox
    category: all
  TextControl:
    display_name: Text
    category: all
  ButtonControl:
    display_name: Button
    category: all
  TextboxControl:
    display_name: Textfield
    category: all
  HeadingControl:
    display_name: Headings
    category: all
  AlertControl:
    display_name: Alert
    category: all
  ButtonGroupControl:
    display_name: Button Group
    category: all
  PaginationControl:
    display_name: Pagination
    category: all
  NavbarControl:
    display_name: Navigation Bar
    category: all
  ButtonAddons:
    display_name: Button Addons
    category: all
